service: myserverlessproject

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  profile: serverlessUser

functions:
  graphql:
    handler: index.server
    events:
    - http:
        path: /
        method: post
        cors: true
        
  playground:
    handler: index.playground
    events:
    - http:
        path: /
        method: get
        cors: true